// client-vue/src/components/EmptyState.vue
<template>
  <div class="empty">
    <div class="feedback">
      <h2 class="R">{{ t('You have no conversations.') }}</h2>
      <a class="button addwave R" href="#" @click.prevent="appStore.openEditWave()">
        {{ t('Add conversation +') }}
      </a>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useAppStore } from '@/stores/app'
import { t } from '@/utils/i18n'

const appStore = useAppStore()
</script>

// client-react/src/components/EmptyState.tsx
import { useAppStore } from '@/stores/appStore'
import { t } from '@/utils/i18n'

export default function EmptyState() {
  const openEditWave = useAppStore(state => state.openEditWave)

  return (
    <div className="empty">
      <div className="feedback">
        <h2 className="R">{t('You have no conversations.')}</h2>
        <a 
          className="button addwave R" 
          href="#" 
          onClick={(e) => { e.preventDefault(); openEditWave() }}
        >
          {t('Add conversation +')}
        </a>
      </div>
    </div>
  )
}
