// client-vue/src/components/WaveReplyForm.vue
<template>
  <div class="notification replyform">
    <form class="add-message" method="post" @submit.prevent="handleSubmit">
      <textarea
        v-model="message"
        name="message"
        :placeholder="t('Add message')"
        class="R"
        @keydown="handleKeyDown"
        ref="textarea"
      ></textarea>
      <p class="inline-help mhide">
        <button type="submit" class="button sendmsg R">
          {{ t('Save message') }}
        </button>
        <span class="R hint">{{ t('Press Return to send, Shift-Return to break line.') }}</span>
      </p>
    </form>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { communicator } from '@/services/communicator'
import { t } from '@/utils/i18n'

interface Props {
  waveId: string
}

const props = defineProps<Props>()

const message = ref('')
const textarea = ref<HTMLTextAreaElement>()

function handleSubmit() {
  if (!message.value.trim()) return
  
  communicator.sendMessage(message.value, props.waveId, null)
  message.value = ''
  
  // Focus back on textarea
  textarea.value?.focus()
}

function handleKeyDown(event: KeyboardEvent) {
  if (event.key === 'Enter' && !event.shiftKey) {
    event.preventDefault()
    handleSubmit()
  }
}
</script>

// client-react/src/components/WaveReplyForm.tsx
import { useState, useRef, FormEvent, KeyboardEvent } from 'react'
import { communicator } from '@/services/communicator'
import { t } from '@/utils/i18n'

interface Props {
  waveId: string
}

export default function WaveReplyForm({ waveId }: Props) {
  const [message, setMessage] = useState('')
  const textareaRef = useRef<HTMLTextAreaElement>(null)

  const handleSubmit = (e: FormEvent) => {
    e.preventDefault()
    if (!message.trim()) return
    
    communicator.sendMessage(message, waveId, null)
    setMessage('')
    textareaRef.current?.focus()
  }

  const handleKeyDown = (e: KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      handleSubmit(e)
    }
  }

  return (
    <div className="notification replyform">
      <form className="add-message" method="post" onSubmit={handleSubmit}>
        <textarea
          ref={textareaRef}
          value={message}
          onChange={(e) => setMessage(e.target.value)}
          name="message"
          placeholder={t('Add message')}
          className="R"
          onKeyDown={handleKeyDown}
        />
        <p className="inline-help mhide">
          <button type="submit" className="button sendmsg R">
            {t('Save message')}
          </button>
          <span className="R hint">{t('Press Return to send, Shift-Return to break line.')}</span>
        </p>
      </form>
    </div>
  )
}
