// client-vue/src/components/WaveListItem.vue
<template>
  <RouterLink :to="`/wave/${wave._id}`" class="waveitem">
    <h2>{{ wave.title }}</h2>
    <p class="meta mhide">
      <span class="usercount R">{{ userCount }} {{ t('participants') }}</span>
      <span class="piros" v-if="unreadCount > 0">{{ unreadCount }}</span>
    </p>
  </RouterLink>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { RouterLink } from 'vue-router'
import type { Wave } from '@/types'
import { useWaveStore } from '@/stores/wave'
import { useMessageStore } from '@/stores/message'
import { t } from '@/utils/i18n'

interface Props {
  wave: Wave
}

const props = defineProps<Props>()

const waveStore = useWaveStore()
const messageStore = useMessageStore()

const userCount = computed(() => props.wave.userIds.length)
const unreadCount = computed(() => waveStore.getWaveUnreadCount(props.wave._id))
</script>

// client-react/src/components/WaveListItem.tsx
import { Link, useParams } from 'react-router-dom'
import type { Wave } from '@/types'
import { useWaveStore } from '@/stores/waveStore'
import { t } from '@/utils/i18n'

interface Props {
  wave: Wave
}

export default function WaveListItem({ wave }: Props) {
  const { id } = useParams<{ id: string }>()
  const userCount = wave.userIds.length
  const unreadCount = useWaveStore(state => state.getWaveUnreadCount(wave._id))
  const isOpen = id === wave._id

  return (
    <Link 
      to={`/wave/${wave._id}`} 
      className={`waveitem${isOpen ? ' open' : ''}`}
    >
      <h2>{wave.title}</h2>
      <p className="meta mhide">
        <span className="usercount R">{userCount} {t('participants')}</span>
        {unreadCount > 0 && <span className="piros">{unreadCount}</span>}
      </p>
    </Link>
  )
}
