// client-react/src/views/WavesView.tsx
import { useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { useWaveStore } from '@/stores/waveStore'
import { useAppStore } from '@/stores/appStore'
import { t } from '@/utils/i18n'

export default function WavesView() {
  const navigate = useNavigate()
  const activeWaves = useWaveStore(state => state.activeWaves())
  const openEditWave = useAppStore(state => state.openEditWave)

  useEffect(() => {
    if (activeWaves.length > 0) {
      const lastWave = activeWaves[activeWaves.length - 1]
      navigate(`/wave/${lastWave._id}`)
    }
  }, [activeWaves, navigate])

  return (
    <div className="empty">
      <div className="feedback">
        <h2 className="R">{t('You have no conversations.')}</h2>
        <a 
          className="button addwave R" 
          href="#" 
          onClick={(e) => { e.preventDefault(); openEditWave() }}
        >
          {t('Add conversation +')}
        </a>
      </div>
    </div>
  )
}

// client-vue/src/views/WavesView.vue
<template>
  <div class="empty">
    <div class="feedback">
      <h2 class="R">{{ t('You have no conversations.') }}</h2>
      <a class="button addwave R" href="#" @click.prevent="appStore.openEditWave()">
        {{ t('Add conversation +') }}
      </a>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useWaveStore } from '@/stores/wave'
import { useAppStore } from '@/stores/app'
import { t } from '@/utils/i18n'

const router = useRouter()
const waveStore = useWaveStore()
const appStore = useAppStore()

onMounted(() => {
  // If there are waves, redirect to the last one
  if (waveStore.activeWaves.length > 0) {
    const lastWave = waveStore.activeWaves[waveStore.activeWaves.length - 1]
    router.push(`/wave/${lastWave._id}`)
  }
})
</script>
