// client-vue/src/components/WaveReplyForm.vue
<template>
  <div class="notification replyform">
    <form class="add-message" method="post" @submit.prevent="handleSubmit">
      <textarea
        v-model="message"
        name="message"
        :placeholder="t('Add message')"
        class="R"
        @keydown="handleKeyDown"
        ref="textarea"
      ></textarea>
      <p class="inline-help mhide">
        <button type="submit" class="button sendmsg R">
          {{ t('Save message') }}
        </button>
        <span class="R hint">{{ t('Press Return to send, Shift-Return to break line.') }}</span>
      </p>
    </form>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { communicator } from '@/services/communicator'
import { t } from '@/utils/i18n'

interface Props {
  waveId: string
}

const props = defineProps<Props>()

const message = ref('')
const textarea = ref<HTMLTextAreaElement>()

function handleSubmit() {
  if (!message.value.trim()) return
  
  communicator.sendMessage(message.value, props.waveId, null)
  message.value = ''
  
  // Focus back on textarea
  textarea.value?.focus()
}

function handleKeyDown(event: KeyboardEvent) {
  if (event.key === 'Enter' && !event.shiftKey) {
    event.preventDefault()
    handleSubmit()
  }
}
</script>

// client-react/src/WaveReplyForm.tsx
import { MouseEventHandler, useState } from 'react'
import './WaveReplyForm.css'
import { Wave } from './WaveStore'

const WaveReplyForm = ({ wave }: { wave: Wave }) => {
  const [messageText, setMessageText] = useState('')

  function sendMessage(e?: React.MouseEvent<HTMLButtonElement>) {
    e?.preventDefault()
    wave.sendMessage(messageText)
    setMessageText('')
  }

  function handleKeydown(e: any) {
    if (!e.shiftKey && 13 === e.keyCode) {
      //enter
      e.preventDefault()
      sendMessage()
    } else if (32 === e.keyCode && ' ' === messageText) {
      //space
      e.preventDefault()
      wave.jumpToNextUnread()
    } else if (!e.shiftKey && 9 === e.keyCode) {
      //tab
      // e.preventDefault();
      // this.mentionUser();
    }
    e.stopPropagation()
  }

  return (
    <div className="notification replyform">
      <form className="add-message" method="post">
        <textarea
          name="message"
          placeholder="Add message"
          className="R"
          value={messageText}
          onChange={(e) => setMessageText(e.target.value)}
          onKeyDown={handleKeydown}
        ></textarea>
        <p className="inline-help mhide">
          <button
            type="button"
            className="button sendmsg R"
            onClick={sendMessage}
          >
            Save message
          </button>{' '}
          <span className="R hint">
            Press Return to send, Shift-Return to break line.
          </span>
        </p>
      </form>
    </div>
  )
}

export default WaveReplyForm
